name: OpenLark Bot Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'data/**'
      - 'requirements.txt'
      - '.env.example'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment package
      run: |
        # 创建部署包
        mkdir -p deployment
        cp -r *.py data deployment/
        cp requirements.txt deployment/
        cp .env.example deployment/.env.example
        
        # 创建部署说明
        cat > deployment/README.md << 'EOF'
        # OpenLark Bot 部署包
        
        ## 快速开始
        
        1. 安装依赖: pip install -r requirements.txt
        2. 配置环境变量: cp .env.example .env 并编辑
        3. 启动服务: python sdk_connect.py
        
        ## 环境变量说明
        
        请参考项目根目录的 README.md 文件
        EOF
        
        # 打包
        tar -czf openlark-bot-deployment.tar.gz deployment/

    - name: Upload deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: openlark-bot-deployment
        path: openlark-bot-deployment.tar.gz

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: openlark-bot-deployment.tar.gz
        generate_release_notes: true
